### ISSUE TITLE
[Feature Request] Support for {{date}} and {{time}} format

### ISSUE THREAD

**Issue by FelipeRearden** [LostPaul/ob-open-files-with-commands#3]
Hello @

First of all, thank you very much for this amazing plugin !!!

My FR is simple, to explain: would be amazing if the **file path text field** support `{{date}}` and `{{time}}`   just like the Core Plugin **Templates**

![7351929E-7E0A-4619-A7C5-5B22432D302B](https://user-images.githubusercontent.com/85180696/225313968-8cd04a39-bbd0-4710-8731-c03bed314013.jpeg)

### My Workflow 

This way, I could create a **single** command to open **Daily Notes**

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by LostPaul** [comment]
Good idea I'll consider adding it.
> This way, I could create a single command to open Daily Notes

Isn't this exactly what you need?
![x1rlbqeALsZY3taG3LxP](https://user-images.githubusercontent.com/70213368/225333367-c7a63611-bcee-4701-9338-9266ddf54996.png)

Or what do you mean?

**Comment by FelipeRearden** [comment]
> Good idea I'll consider adding it.

Great ! Thanks for the reply @LostPaul ! 

> > This way, I could create a single command to open Daily Notes
> 
> Isn't this exactly what you need? 

No, I have a more complex workflow for daily notes. 

> Or what do you mean?

Let me explain....

1️⃣ I have more than one Daily notes. One for work and one for personal . This way I have these two "syntax"  for daily notes:

→ WRK_{{YYYY-MM-DD}}.md
→ LFE_{{YYYY-MM-DD}}.md

This way I cant the daily notes command to open these  daily files :)

2️⃣ I wanna a command to open these notes on the **Sidebars**:
→ Personal on  **Right Sidebar** 
→ Work  on **Left Sidebar.**

---

Let me know if you need more information :)

Have a great day!!!!

**Comment by LostPaul** [comment]
Alright thanks for the explanation

**Comment by FelipeRearden** [comment]
Great @LostPaul !

**Comment by LostPaul** [comment]
@FelipeRearden Sorry for the long delay but this has been added with the latest update of the plugin.
